# Generated by Django 5.2.6 on 2026-09-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('title', models.CharField(max_length=180, verbose_name='Tên giải thưởng')),
                ('issuer', models.CharField(max_length=140, verbose_name='Đơn vị cấp')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Năm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('credential_url', models.URLField(blank=True, verbose_name='Minh chứng')),
            ],
            options={
                'verbose_name': 'Giải thưởng',
                'verbose_name_plural': 'Giải thưởng',
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('name', models.CharField(max_length=180, verbose_name='Chứng chỉ')),
                ('issuer', models.CharField(max_length=140, verbose_name='Đơn vị cấp')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('expires_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('credential_id', models.CharField(blank=True, max_length=120, verbose_name='Mã chứng chỉ')),
                ('credential_url', models.URLField(blank=True, verbose_name='Đường dẫn')),
            ],
            options={
                'verbose_name': 'Chứng chỉ',
                'verbose_name_plural': 'Chứng chỉ',
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=180, verbose_name='Chủ đề')),
                ('message', models.TextField(max_length=3000, verbose_name='Nội dung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn liên hệ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('school', models.CharField(max_length=180, verbose_name='Trường')),
                ('degree', models.CharField(max_length=150, verbose_name='Bằng cấp')),
                ('field_of_study', models.CharField(blank=True, max_length=150, verbose_name='Chuyên ngành')),
                ('start_year', models.PositiveSmallIntegerField(verbose_name='Năm bắt đầu')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Năm kết thúc')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Xếp loại / GPA')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('school_url', models.URLField(blank=True, verbose_name='Website trường')),
            ],
            options={
                'verbose_name': 'Học vấn',
                'verbose_name_plural': 'Học vấn',
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('company', models.CharField(max_length=120, verbose_name='Công ty')),
                ('role', models.CharField(max_length=120, verbose_name='Vị trí')),
                ('start_date', models.DateField(verbose_name='Bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Kết thúc')),
                ('is_current', models.BooleanField(default=False, verbose_name='Đang làm việc')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Địa điểm')),
                ('employment_type', models.CharField(blank=True, max_length=50, verbose_name='Hình thức')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='Danh sách JSON, ví dụ ["Tăng tốc độ 40%"]', verbose_name='Điểm nổi bật')),
                ('technologies', models.JSONField(blank=True, default=list, verbose_name='Công nghệ')),
                ('company_url', models.URLField(blank=True, verbose_name='Website công ty')),
            ],
            options={
                'verbose_name': 'Kinh nghiệm',
                'verbose_name_plural': 'Kinh nghiệm',
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Họ và tên')),
                ('headline', models.CharField(max_length=180, verbose_name='Chức danh')),
                ('short_bio', models.TextField(max_length=420, verbose_name='Giới thiệu ngắn')),
                ('long_bio', models.TextField(blank=True, verbose_name='Giới thiệu chi tiết')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Số điện thoại')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Địa điểm')),
                ('availability', models.CharField(default='Open to opportunities', max_length=120, verbose_name='Trạng thái làm việc')),
                ('avatar_url', models.URLField(blank=True, verbose_name='URL ảnh đại diện')),
                ('resume_url', models.URLField(blank=True, verbose_name='URL CV PDF')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, verbose_name='Số năm kinh nghiệm')),
                ('projects_count', models.PositiveSmallIntegerField(default=0, verbose_name='Số dự án')),
                ('coffee_count', models.PositiveIntegerField(default=100, verbose_name='Số ly cà phê')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hồ sơ',
                'verbose_name_plural': 'Hồ sơ',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('title', models.CharField(max_length=140, verbose_name='Tên dự án')),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(max_length=220, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('cover_url', models.URLField(blank=True, verbose_name='URL ảnh bìa')),
                ('live_url', models.URLField(blank=True, verbose_name='Website')),
                ('source_url', models.URLField(blank=True, verbose_name='Mã nguồn')),
                ('technologies', models.JSONField(default=list, verbose_name='Công nghệ')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Năm')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Dự án nổi bật')),
                ('accent', models.CharField(default='#7c3aed', max_length=20, verbose_name='Màu nhấn')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('name', models.CharField(max_length=80, verbose_name='Kỹ năng')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps & Tools'), ('other', 'Khác')], max_length=20, verbose_name='Nhóm')),
                ('level', models.PositiveSmallIntegerField(default=75, verbose_name='Mức độ (%)')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='Icon / mã ngắn')),
            ],
            options={
                'verbose_name': 'Kỹ năng chuyên môn',
                'verbose_name_plural': 'Kỹ năng chuyên môn',
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('label', models.CharField(max_length=50, verbose_name='Tên mạng')),
                ('url', models.URLField(verbose_name='Đường dẫn')),
                ('icon', models.CharField(help_text='github, linkedin, facebook, globe...', max_length=30, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Liên kết',
                'verbose_name_plural': 'Liên kết',
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('name', models.CharField(max_length=100, verbose_name='Kỹ năng mềm')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Mô tả')),
                ('icon', models.CharField(default='sparkles', max_length=30, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Kỹ năng mềm',
                'verbose_name_plural': 'Kỹ năng mềm',
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
    ]
