# Generated by Django 5.2.6 on 2026-09-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.TextField(blank=True, help_text='Logo tải lên từ CMS, tối đa 512 KB', verbose_name='Logo công ty'),
        ),
    ]
