# Generated by Django 5.2.6 on 2026-09-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='award',
            name='issuer_en',
            field=models.CharField(blank=True, max_length=140, verbose_name='Issuer (English)'),
        ),
        migrations.AddField(
            model_name='award',
            name='title_en',
            field=models.CharField(blank=True, max_length=180, verbose_name='Award title (English)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='issuer_en',
            field=models.CharField(blank=True, max_length=140, verbose_name='Issuer (English)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='name_en',
            field=models.CharField(blank=True, max_length=180, verbose_name='Certification name (English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Degree (English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Field of study (English)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='employment_type_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Employment type (English)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='highlights_en',
            field=models.JSONField(blank=True, default=list, help_text='JSON list, e.g. ["Improved performance by 40%"]', verbose_name='Highlights (English)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Role (English)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='availability_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Availability (English)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_en',
            field=models.CharField(blank=True, max_length=180, verbose_name='Job title (English)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='long_bio_en',
            field=models.TextField(blank=True, verbose_name='Detailed bio (English)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio_en',
            field=models.TextField(blank=True, max_length=420, verbose_name='Short bio (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Detailed description (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=220, verbose_name='Tagline (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=140, verbose_name='Project title (English)'),
        ),
        migrations.AddField(
            model_name='softskill',
            name='description_en',
            field=models.CharField(blank=True, max_length=240, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='softskill',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Soft skill (English)'),
        ),
    ]
