# Generated by Django 5.2.6 on 2026-09-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_award_description_en_award_issuer_en_award_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_logo',
            field=models.TextField(blank=True, help_text='Logo tải lên từ CMS, tối đa 512 KB', verbose_name='Logo trường'),
        ),
    ]
