# Generated by Django 5.2.6 on 2026-09-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_education_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_en',
            field=models.CharField(blank=True, max_length=180, verbose_name='School name (English)'),
        ),
    ]
