# Generated by Django 5.2.6 on 2026-09-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_education_school_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Company name (English)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Location (English)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Location (English)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Skill name (English)'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='label_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Social label (English)'),
        ),
    ]
