# Generated by Django 5.2.6 on 2026-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_experience_company_en_experience_location_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='program_type',
            field=models.CharField(choices=[('degree', 'Bằng cấp / Degree'), ('exchange', 'Trao đổi sinh viên / Student exchange'), ('course', 'Khóa học / Course'), ('other', 'Khác / Other')], default='degree', max_length=20, verbose_name='Loại chương trình'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=150, verbose_name='Tên bằng cấp / chương trình'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Degree / program name (English)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='Chỉ dùng cho chương trình bằng cấp', max_length=150, verbose_name='Chuyên ngành'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study_en',
            field=models.CharField(blank=True, help_text='Only used for degree programs', max_length=150, verbose_name='Field of study (English)'),
        ),
    ]
