# Generated by Django 5.2.6 on 2026-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_education_end_month_education_start_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, '01 - Tháng 1 / January'), (2, '02 - Tháng 2 / February'), (3, '03 - Tháng 3 / March'), (4, '04 - Tháng 4 / April'), (5, '05 - Tháng 5 / May'), (6, '06 - Tháng 6 / June'), (7, '07 - Tháng 7 / July'), (8, '08 - Tháng 8 / August'), (9, '09 - Tháng 9 / September'), (10, '10 - Tháng 10 / October'), (11, '11 - Tháng 11 / November'), (12, '12 - Tháng 12 / December')], default=1, verbose_name='Tháng'),
        ),
        migrations.AddField(
            model_name='project',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, '01 - Tháng 1 / January'), (2, '02 - Tháng 2 / February'), (3, '03 - Tháng 3 / March'), (4, '04 - Tháng 4 / April'), (5, '05 - Tháng 5 / May'), (6, '06 - Tháng 6 / June'), (7, '07 - Tháng 7 / July'), (8, '08 - Tháng 8 / August'), (9, '09 - Tháng 9 / September'), (10, '10 - Tháng 10 / October'), (11, '11 - Tháng 11 / November'), (12, '12 - Tháng 12 / December')], default=1, verbose_name='Tháng'),
        ),
    ]
