"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUpRight, Award, BrainCircuit, BriefcaseBusiness, Check, Code2, ExternalLink, Github, GraduationCap, Linkedin, Mail, MapPin, Menu, MessageSquareText, Moon, Send, Sparkles, Sun, Terminal, Trophy, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { demoData } from "@/lib/data";
import { PortfolioData } from "@/lib/types";
import { cn } from "@/lib/utils";

const API=(process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api").replace(/\/$/,"");
const iconMap:Record<string,React.ComponentType<{className?:string}>>={github:Github,linkedin:Linkedin,brain:BrainCircuit,message:MessageSquareText,sparkles:Sparkles};
const formatDate=(value:string|null,current=false)=>current?"Hiện tại":value?new Intl.DateTimeFormat("vi-VN",{month:"2-digit",year:"numeric"}).format(new Date(value)):"";

function SectionTitle({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="section-heading"><p><span>~/</span>{eyebrow}</p><h2>{title}</h2>{copy&&<div>{copy}</div>}</div>}

export function Portfolio(){
  const [data,setData]=useState<PortfolioData>(demoData); const [menu,setMenu]=useState(false); const [dark,setDark]=useState(true); const [sent,setSent]=useState(false); const [sending,setSending]=useState(false); const [filter,setFilter]=useState("all");
  useEffect(()=>{document.documentElement.classList.toggle("dark",dark)},[dark]);
  useEffect(()=>{fetch(`${API}/`).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>d.profile&&setData(d)).catch(()=>{})},[]);
  const p=data.profile!; const categories=useMemo(()=>["all",...Array.from(new Set(data.skills.map(s=>s.category)))],[data.skills]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSending(true);const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));try{const r=await fetch(`${API}/contact/`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw Error();setSent(true);form.reset()}catch{alert("Chưa thể gửi tin nhắn. Bạn có thể liên hệ trực tiếp qua email.")}finally{setSending(false)}};
  return <div className="site-shell">
    <div className="grid-bg"/><div className="orb orb-one"/><div className="orb orb-two"/>
    <header className="nav-wrap"><nav className="nav container"><a href="#home" className="brand"><span>&lt;ST /&gt;</span><i>portfolio.sys</i></a><div className={cn("nav-links",menu&&"open")}>{[["about","Giới thiệu"],["experience","Kinh nghiệm"],["projects","Dự án"],["skills","Kỹ năng"]].map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}<a href="#contact" onClick={()=>setMenu(false)}>Liên hệ <ArrowUpRight/></a></div><div className="nav-actions"><button aria-label="Đổi giao diện" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="mobile-menu" aria-label="Mở menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></nav></header>

    <main>
      <section id="home" className="hero container"><div className="hero-copy"><div className="status-pill"><i/> {p.availability}</div><p className="hello">Xin chào, mình là</p><h1>{p.full_name}<span>.</span></h1><div className="type-line"><span>&gt;</span> {p.headline}<i>_</i></div><p className="hero-intro">{p.short_bio}</p><div className="hero-actions"><Button size="lg" asChild><a href="#projects">Xem dự án <ArrowDown/></a></Button><Button size="lg" variant="outline" asChild><a href={p.resume_url||"#contact"} target={p.resume_url?"_blank":undefined}>Tải CV <ArrowUpRight/></a></Button></div><div className="social-row">{data.socials.map(s=>{const Icon=iconMap[s.icon]||ExternalLink;return <a key={s.id} href={s.url} target="_blank" rel="noreferrer" aria-label={s.label}><Icon/></a>})}</div></div>
        <div className="hero-visual"><div className="code-card"><div className="code-top"><span/><span/><span/><p>developer.ts</p></div><pre><code><em>const</em> developer = {'{'}{`\n`}  name: <b>&quot;{p.full_name}&quot;</b>,{`\n`}  role: <b>&quot;{p.headline}&quot;</b>,{`\n`}  location: <b>&quot;{p.location}&quot;</b>,{`\n`}  mindset: [<b>&quot;build&quot;</b>, <b>&quot;learn&quot;</b>, <b>&quot;ship&quot;</b>],{`\n`}  available: <u>true</u>{`\n`}{'}'};</code></pre><div className="terminal-line"><span>➜</span> building ideas into reality...</div></div><div className="orbit"><Code2/><span/><span/></div></div>
        <div className="metrics">{[[`${p.years_experience}+`,`Năm kinh nghiệm`],[`${p.projects_count}+`,`Dự án hoàn thành`],[`${p.coffee_count}+`,`Cốc cà phê`]].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div>
      </section>

      <section id="about" className="section container about"><SectionTitle eyebrow="about_me" title="Code có mục đích. Thiết kế có lý do."/><div className="about-grid"><div className="portrait-card">{p.avatar_url?<img src={p.avatar_url} alt={p.full_name}/>:<div className="avatar-fallback"><Terminal/><span>YOUR PHOTO</span></div>}<span className="corner tl"/><span className="corner br"/></div><div className="about-copy"><p>{p.long_bio||p.short_bio}</p><div className="info-grid"><div><MapPin/><span>Địa điểm<small>{p.location||"Vietnam"}</small></span></div><div><Mail/><span>Email<small>{p.email}</small></span></div></div><div className="principles"><div><span>01</span><p><strong>Clean code</strong><small>Dễ đọc, dễ mở rộng</small></p></div><div><span>02</span><p><strong>User first</strong><small>Trải nghiệm là trọng tâm</small></p></div><div><span>03</span><p><strong>Keep learning</strong><small>Luôn tiến về phía trước</small></p></div></div></div></div></section>

      <section id="experience" className="section section-tint"><div className="container"><SectionTitle eyebrow="journey.log" title="Hành trình phát triển" copy="Những cột mốc đã tạo nên cách tôi tư duy và xây dựng sản phẩm."/><div className="journey-grid"><div><h3><BriefcaseBusiness/> Kinh nghiệm</h3><div className="timeline">{data.experiences.map(x=><article key={x.id}><i/><div className="timeline-time">{formatDate(x.start_date)} — {formatDate(x.end_date,x.is_current)}</div><div className="experience-heading">{x.company_logo&&<img src={x.company_logo} alt={`Logo ${x.company}`}/>}<div><h4>{x.role}</h4><a href={x.company_url||undefined}>{x.company}</a></div></div><p>{x.description}</p><ul>{x.highlights.map(v=><li key={v}><Check/>{v}</li>)}</ul><div className="tag-row">{x.technologies.map(t=><Badge key={t}>{t}</Badge>)}</div></article>)}</div></div><div><h3><GraduationCap/> Học vấn</h3><div className="timeline">{data.education.map(x=><article key={x.id}><i/><div className="timeline-time">{x.start_year} — {x.end_year||"Hiện tại"}</div><h4>{x.degree}</h4><a href={x.school_url||undefined}>{x.school}</a><p>{x.field_of_study}{x.grade&&` · ${x.grade}`}<br/>{x.description}</p></article>)}</div></div></div></div></section>

      <section id="projects" className="section container"><SectionTitle eyebrow="selected_work" title="Dự án nổi bật" copy="Một vài sản phẩm mình đã thiết kế, xây dựng và đưa vào vận hành."/><div className="project-grid">{data.projects.map((x,i)=><article className={cn("project-card",i===0&&"featured")} key={x.id} style={{"--accent":x.accent} as React.CSSProperties}><div className="project-art">{x.cover_url?<img src={x.cover_url} alt=""/>:<><div className="project-number">0{i+1}</div><Code2/></>}<span>{x.year}</span></div><div className="project-body"><div><p>FEATURED / {String(i+1).padStart(2,"0")}</p><h3>{x.title}</h3></div><p>{x.tagline}</p><div className="tag-row">{x.technologies.map(t=><Badge key={t}>{t}</Badge>)}</div><div className="project-links">{x.live_url&&<a href={x.live_url} target="_blank">Live demo <ExternalLink/></a>}{x.source_url&&<a href={x.source_url} target="_blank">Source <Github/></a>}</div></div></article>)}</div></section>

      <section id="skills" className="section section-tint"><div className="container"><SectionTitle eyebrow="tech_stack" title="Công cụ & năng lực"/><div className="skill-filters">{categories.map(c=><button className={filter===c?"active":""} key={c} onClick={()=>setFilter(c)}>{c==="all"?"Tất cả":c}</button>)}</div><div className="skill-grid">{data.skills.filter(s=>filter==="all"||s.category===filter).map(s=><div className="skill-card" key={s.id}><span>{s.icon||s.name.slice(0,2)}</span><div><strong>{s.name}</strong><small>{s.category}</small></div><p>{s.level}%</p><i><u style={{width:`${s.level}%`}}/></i></div>)}</div><h3 className="soft-title">Beyond the code</h3><div className="soft-grid">{data.soft_skills.map(s=>{const Icon=iconMap[s.icon]||Sparkles;return <article key={s.id}><Icon/><div><h4>{s.name}</h4><p>{s.description}</p></div></article>})}</div></div></section>

      {(data.awards.length>0||data.certifications.length>0)&&<section className="section container"><SectionTitle eyebrow="achievements" title="Dấu ấn & chứng nhận"/><div className="achievement-grid">{data.awards.map(a=><article key={`a${a.id}`}><Trophy/><div><span>{a.year} · {a.issuer}</span><h3>{a.title}</h3><p>{a.description}</p>{a.credential_url&&<a href={a.credential_url}>Xem minh chứng <ArrowUpRight/></a>}</div></article>)}{data.certifications.map(c=><article key={`c${c.id}`}><Award/><div><span>{c.issuer}</span><h3>{c.name}</h3><p>{c.credential_id&&`ID: ${c.credential_id}`}</p>{c.credential_url&&<a href={c.credential_url}>Xem chứng chỉ <ArrowUpRight/></a>}</div></article>)}</div></section>}

      <section id="contact" className="section contact-section"><div className="container contact-grid"><div><SectionTitle eyebrow="contact.init" title="Có một ý tưởng? Cùng biến nó thành hiện thực."/><p>Mình luôn sẵn lòng trao đổi về sản phẩm, công nghệ và những cơ hội hợp tác thú vị.</p><a className="direct-email" href={`mailto:${p.email}`}><Mail/>{p.email}</a><div className="contact-status"><i/> Thường phản hồi trong vòng 24 giờ</div></div><form onSubmit={submit}>{sent?<div className="sent-state"><Check/><h3>Tin nhắn đã được gửi!</h3><p>Cảm ơn bạn. Mình sẽ phản hồi sớm nhất có thể.</p><Button type="button" variant="outline" onClick={()=>setSent(false)}>Gửi tin khác</Button></div>:<><div className="field-row"><label>Họ và tên<input name="name" maxLength={120} placeholder="Nguyễn Văn A" required/></label><label>Email<input name="email" type="email" placeholder="hello@email.com" required/></label></div><label>Chủ đề<input name="subject" maxLength={180} placeholder="Mình muốn trao đổi về..." required/></label><label>Nội dung<textarea name="message" rows={5} maxLength={3000} placeholder="Kể mình nghe về ý tưởng của bạn nhé..." required/></label><Button size="lg" disabled={sending}>{sending?"Đang gửi...":"Gửi tin nhắn"}<Send/></Button></>}</form></div></section>
    </main>
    <footer><div className="container"><a href="#home" className="brand"><span>&lt;ST /&gt;</span></a><p>Designed & built with <span>♥</span> and a lot of coffee.</p><div><a href={`${API.replace(/\/api$/,'')}/admin/`} target="_blank">CMS</a><a href="#home">Lên đầu <ArrowUpRight/></a></div></div></footer>
  </div>
}
