"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUpRight, Award, BrainCircuit, BriefcaseBusiness, Check, Code2, ExternalLink, Github, GraduationCap, Linkedin, Mail, MapPin, Menu, MessageSquareText, Moon, Send, Sparkles, Sun, Terminal, Trophy, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { demoData } from "@/lib/data";
import { PortfolioData } from "@/lib/types";
import { cn } from "@/lib/utils";

const API=(process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api").replace(/\/$/,"");
const iconMap:Record<string,React.ComponentType<{className?:string}>>={github:Github,linkedin:Linkedin,brain:BrainCircuit,message:MessageSquareText,sparkles:Sparkles};
const formatDate=(value:string|null,current=false,lang:"vi"|"en"="vi")=>current?(lang==="vi"?"Hiện tại":"Present"):value?new Intl.DateTimeFormat(lang==="vi"?"vi-VN":"en-US",{month:"short",year:"numeric"}).format(new Date(value)):"";

function SectionTitle({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="section-heading"><p><span>~/</span>{eyebrow}</p><h2>{title}</h2>{copy&&<div>{copy}</div>}</div>}

export function Portfolio(){
  const [data,setData]=useState<PortfolioData>(demoData); const [menu,setMenu]=useState(false); const [dark,setDark]=useState(true); const [lang,setLang]=useState<"vi"|"en">("vi"); const [sent,setSent]=useState(false); const [sending,setSending]=useState(false); const [filter,setFilter]=useState("all");
  useEffect(()=>{document.documentElement.classList.toggle("dark",dark)},[dark]);
  useEffect(()=>{fetch(`${API}/`).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>d.profile&&setData(d)).catch(()=>{})},[]);
  const p=data.profile!; const t=(vi:string,en:string)=>lang==="vi"?vi:en; const local=(item:Record<string,any>,field:string)=>lang==="en"&&item[`${field}_en`]?String(item[`${field}_en`]):String(item[field]||""); const localList=(item:Record<string,any>,field:string)=>lang==="en"&&Array.isArray(item[`${field}_en`])?item[`${field}_en`] as string[]:item[field] as string[]||[]; const categories=useMemo(()=>["all",...Array.from(new Set(data.skills.map(s=>s.category)))],[data.skills]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSending(true);const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));try{const r=await fetch(`${API}/contact/`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw Error();setSent(true);form.reset()}catch{alert(t("Chưa thể gửi tin nhắn. Bạn có thể liên hệ trực tiếp qua email.","Unable to send your message. Please contact me directly by email."))}finally{setSending(false)}};
  return <div className="site-shell">
    <div className="grid-bg"/><div className="orb orb-one"/><div className="orb orb-two"/>
    <header className="nav-wrap"><nav className="nav container"><a href="#home" className="brand"><span>&lt;ST /&gt;</span><i>portfolio.sys</i></a><div className={cn("nav-links",menu&&"open")}>{[["about",t("Giới thiệu","About")],["experience",t("Kinh nghiệm","Experience")],["projects",t("Dự án","Projects")],["skills",t("Kỹ năng","Skills")]].map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}<a href="#contact" onClick={()=>setMenu(false)}>{t("Liên hệ","Contact")} <ArrowUpRight/></a></div><div className="nav-actions"><button className="lang-switch" aria-label={t("Chuyển sang tiếng Anh","Switch to Vietnamese")} onClick={()=>setLang(lang==="vi"?"en":"vi")}>{lang==="vi"?"EN":"VI"}</button><button aria-label={t("Đổi giao diện","Toggle theme")} onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="mobile-menu" aria-label={t("Mở menu","Open menu")} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></nav></header>

    <main>
      <section id="home" className="hero container"><div className="hero-copy"><div className="status-pill"><i/> {local(p,"availability")}</div><p className="hello">{t("Xin chào, mình là","Hello, I am")}</p><h1>{p.full_name}<span>.</span></h1><div className="type-line"><span>&gt;</span> {local(p,"headline")}<i>_</i></div><p className="hero-intro">{local(p,"short_bio")}</p><div className="hero-actions"><Button size="lg" asChild><a href="#projects">{t("Xem dự án","View projects")} <ArrowDown/></a></Button><Button size="lg" variant="outline" asChild><a href={p.resume_url||"#contact"} target={p.resume_url?"_blank":undefined}>{t("Tải CV","Download CV")} <ArrowUpRight/></a></Button></div><div className="social-row">{data.socials.map(s=>{const Icon=iconMap[s.icon]||ExternalLink;return <a key={s.id} href={s.url} target="_blank" rel="noreferrer" aria-label={s.label}><Icon/></a>})}</div></div>
        <div className="hero-visual"><div className="code-card"><div className="code-top"><span/><span/><span/><p>engineer.ts</p></div><pre><code><em>const</em> engineer = {'{'}{`\n`}  name: <b>&quot;{p.full_name}&quot;</b>,{`\n`}  role: <b>&quot;{local(p,"headline")}&quot;</b>,{`\n`}  location: <b>&quot;{p.location}&quot;</b>,{`\n`}  mindset: [<b>&quot;operate&quot;</b>, <b>&quot;automate&quot;</b>, <b>&quot;improve&quot;</b>],{`\n`}  available: <u>true</u>{`\n`}{'}'};</code></pre><div className="terminal-line"><span>➜</span> {t("đang vận hành những hệ thống đáng tin cậy...","operating reliable systems...")}</div></div><div className="orbit"><Code2/><span/><span/></div></div>
        <div className="metrics">{[[`${p.years_experience}+`,t("Năm kinh nghiệm","Years experience")],[`${p.projects_count}+`,t("Dự án hoàn thành","Projects delivered")],[`${p.coffee_count}+`,t("Cốc cà phê","Cups of coffee")]].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div>
      </section>

      <section id="about" className="section container about"><SectionTitle eyebrow="about_me" title={t("Hệ thống có chủ đích. Vận hành có kỷ luật.","Purposeful systems. Disciplined operations.")}/><div className="about-grid"><div className="portrait-card">{p.avatar_url?<img src={p.avatar_url} alt={p.full_name}/>:<div className="avatar-fallback"><Terminal/><span>{t("ẢNH CỦA BẠN","YOUR PHOTO")}</span></div>}<span className="corner tl"/><span className="corner br"/></div><div className="about-copy"><p>{local(p,"long_bio")||local(p,"short_bio")}</p><div className="info-grid"><div><MapPin/><span>{t("Địa điểm","Location")}<small>{p.location||"Vietnam"}</small></span></div><div><Mail/><span>Email<small>{p.email}</small></span></div></div><div className="principles"><div><span>01</span><p><strong>Reliable first</strong><small>{t("Ổn định và có thể phục hồi","Stable and recoverable")}</small></p></div><div><span>02</span><p><strong>Automate wisely</strong><small>{t("Tự động hóa có kiểm soát","Automation with control")}</small></p></div><div><span>03</span><p><strong>Keep learning</strong><small>{t("Luôn tiến về phía trước","Always moving forward")}</small></p></div></div></div></div></section>

      <section id="experience" className="section section-tint"><div className="container"><SectionTitle eyebrow="journey.log" title={t("Hành trình phát triển","Professional journey")} copy={t("Những cột mốc tạo nên cách tôi tư duy và vận hành hệ thống.","Milestones that shaped how I think about and operate systems.")}/><div className="journey-grid"><div><h3><BriefcaseBusiness/> {t("Kinh nghiệm","Experience")}</h3><div className="timeline">{data.experiences.length?data.experiences.map(x=><article key={x.id}><i/><div className="timeline-time">{formatDate(x.start_date,false,lang)} — {formatDate(x.end_date,x.is_current,lang)}</div><div className="experience-heading">{x.company_logo&&<img src={x.company_logo} alt={`Logo ${x.company}`}/>}<div><h4>{local(x,"role")}</h4><a href={x.company_url||undefined}>{x.company}</a></div></div><p>{local(x,"description")}</p><ul>{localList(x,"highlights").map(v=><li key={v}><Check/>{v}</li>)}</ul><div className="tag-row">{x.technologies.map(v=><Badge key={v}>{v}</Badge>)}</div></article>):<p className="cms-empty">{t("Nội dung sẽ được cập nhật từ CMS.","Content will be added through the CMS.")}</p>}</div></div><div><h3><GraduationCap/> {t("Học vấn","Education")}</h3><div className="timeline">{data.education.length?data.education.map(x=><article key={x.id}><i/><div className="timeline-time">{x.start_year} — {x.end_year||t("Hiện tại","Present")}</div><h4>{local(x,"degree")}</h4><a href={x.school_url||undefined}>{x.school}</a><p>{local(x,"field_of_study")}{x.grade&&` · ${x.grade}`}<br/>{local(x,"description")}</p></article>):<p className="cms-empty">{t("Nội dung sẽ được cập nhật từ CMS.","Content will be added through the CMS.")}</p>}</div></div></div></div></section>

      <section id="projects" className="section container"><SectionTitle eyebrow="selected_work" title={t("Dự án nổi bật","Selected projects")} copy={t("Những hệ thống và sản phẩm đã được xây dựng, triển khai và vận hành.","Systems and products built, deployed, and operated.")}/>{data.projects.length?<div className="project-grid">{data.projects.map((x,i)=><article className={cn("project-card",i===0&&"featured")} key={x.id} style={{"--accent":x.accent} as React.CSSProperties}><div className="project-art">{x.cover_url?<img src={x.cover_url} alt=""/>:<><div className="project-number">0{i+1}</div><Code2/></>}<span>{x.year}</span></div><div className="project-body"><div><p>{t("NỔI BẬT","FEATURED")} / {String(i+1).padStart(2,"0")}</p><h3>{local(x,"title")}</h3></div><p>{local(x,"tagline")}</p><div className="tag-row">{x.technologies.map(v=><Badge key={v}>{v}</Badge>)}</div><div className="project-links">{x.live_url&&<a href={x.live_url} target="_blank">Live demo <ExternalLink/></a>}{x.source_url&&<a href={x.source_url} target="_blank">Source <Github/></a>}</div></div></article>)}</div>:<p className="cms-empty standalone">{t("Chưa có dự án được xuất bản. Hãy thêm từ CMS.","No published projects yet. Add them from the CMS.")}</p>}</section>

      <section id="skills" className="section section-tint"><div className="container"><SectionTitle eyebrow="tech_stack" title={t("Công cụ & năng lực","Tools & capabilities")}/>{data.skills.length?<><div className="skill-filters">{categories.map(c=><button className={filter===c?"active":""} key={c} onClick={()=>setFilter(c)}>{c==="all"?t("Tất cả","All"):c}</button>)}</div><div className="skill-grid">{data.skills.filter(s=>filter==="all"||s.category===filter).map(s=><div className="skill-card" key={s.id}><span>{s.icon||s.name.slice(0,2)}</span><div><strong>{s.name}</strong><small>{s.category}</small></div><p>{s.level}%</p><i><u style={{width:`${s.level}%`}}/></i></div>)}</div></>:<p className="cms-empty standalone">{t("Kỹ năng sẽ được cập nhật từ CMS.","Skills will be added through the CMS.")}</p>}{data.soft_skills.length>0&&<><h3 className="soft-title">{t("Năng lực ngoài kỹ thuật","Beyond the code")}</h3><div className="soft-grid">{data.soft_skills.map(s=>{const Icon=iconMap[s.icon]||Sparkles;return <article key={s.id}><Icon/><div><h4>{local(s,"name")}</h4><p>{local(s,"description")}</p></div></article>})}</div></>}</div></section>

      {(data.awards.length>0||data.certifications.length>0)&&<section className="section container"><SectionTitle eyebrow="achievements" title={t("Dấu ấn & chứng nhận","Awards & certifications")}/><div className="achievement-grid">{data.awards.map(a=><article key={`a${a.id}`}><Trophy/><div><span>{a.year} · {local(a,"issuer")}</span><h3>{local(a,"title")}</h3><p>{local(a,"description")}</p>{a.credential_url&&<a href={a.credential_url}>{t("Xem minh chứng","View credential")} <ArrowUpRight/></a>}</div></article>)}{data.certifications.map(c=><article key={`c${c.id}`}><Award/><div><span>{local(c,"issuer")}</span><h3>{local(c,"name")}</h3><p>{c.credential_id&&`ID: ${c.credential_id}`}</p>{c.credential_url&&<a href={c.credential_url}>{t("Xem chứng chỉ","View certificate")} <ArrowUpRight/></a>}</div></article>)}</div></section>}

      <section id="contact" className="section contact-section"><div className="container contact-grid"><div><SectionTitle eyebrow="contact.init" title={t("Có một ý tưởng? Cùng biến nó thành hiện thực.","Have an idea? Let's make it real.")}/><p>{t("Mình luôn sẵn lòng trao đổi về hệ thống, hạ tầng và những cơ hội hợp tác thú vị.","I am always open to discussing systems, infrastructure, and meaningful opportunities.")}</p><a className="direct-email" href={`mailto:${p.email}`}><Mail/>{p.email}</a><div className="contact-status"><i/> {t("Thường phản hồi trong vòng 24 giờ","Usually replies within 24 hours")}</div></div><form onSubmit={submit}>{sent?<div className="sent-state"><Check/><h3>{t("Tin nhắn đã được gửi!","Message sent!")}</h3><p>{t("Cảm ơn bạn. Mình sẽ phản hồi sớm nhất có thể.","Thank you. I will get back to you soon.")}</p><Button type="button" variant="outline" onClick={()=>setSent(false)}>{t("Gửi tin khác","Send another")}</Button></div>:<><div className="field-row"><label>{t("Họ và tên","Full name")}<input name="name" maxLength={120} placeholder={t("Nguyễn Văn A","Your name")} required/></label><label>Email<input name="email" type="email" placeholder="hello@email.com" required/></label></div><label>{t("Chủ đề","Subject")}<input name="subject" maxLength={180} placeholder={t("Mình muốn trao đổi về...","I'd like to discuss...")} required/></label><label>{t("Nội dung","Message")}<textarea name="message" rows={5} maxLength={3000} placeholder={t("Kể mình nghe về ý tưởng của bạn nhé...","Tell me about your idea...")} required/></label><Button size="lg" disabled={sending}>{sending?t("Đang gửi...","Sending..."):t("Gửi tin nhắn","Send message")}<Send/></Button></>}</form></div></section>
    </main>
    <footer><div className="container"><a href="#home" className="brand"><span>&lt;ST /&gt;</span></a><p>{t("Thiết kế & xây dựng với","Designed & built with")} <span>♥</span> {t("và rất nhiều cà phê.","and a lot of coffee.")}</p><div><a href={`${API.replace(/\/api$/,'')}/admin/`} target="_blank">CMS</a><a href="#home">{t("Lên đầu","Back to top")} <ArrowUpRight/></a></div></div></footer>
  </div>
}
