import { PortfolioData } from "./types";
export const demoData: PortfolioData = {
  profile: {full_name:"Sơn Tân", headline:"Full-stack Developer", short_bio:"Tôi xây dựng những sản phẩm số nhanh, đẹp và có chiều sâu — từ trải nghiệm người dùng đến hệ thống phía sau.", long_bio:"Một lập trình viên yêu thích việc biến bài toán phức tạp thành sản phẩm đơn giản, đáng tin cậy. Tôi quan tâm đến kiến trúc hệ thống, chất lượng giao diện và những chi tiết khiến trải nghiệm trở nên tự nhiên.", email:"hello@example.com", phone:"", location:"Ho Chi Minh City, Vietnam", availability:"Sẵn sàng cho cơ hội mới", avatar_url:"", resume_url:"", years_experience:2, projects_count:12, coffee_count:842},
  socials:[{id:1,label:"GitHub",url:"https://github.com",icon:"github"},{id:2,label:"LinkedIn",url:"https://linkedin.com",icon:"linkedin"}],
  experiences:[{id:1,company:"Your Company",company_logo:"",role:"Software Engineer",start_date:"2024-01-01",end_date:null,is_current:true,location:"Ho Chi Minh City",employment_type:"Full-time",description:"Phát triển sản phẩm web có hiệu năng cao và trải nghiệm nhất quán.",highlights:["Thiết kế API và luồng dữ liệu có khả năng mở rộng","Cải thiện hiệu năng và chất lượng trải nghiệm"],technologies:["Django","Next.js","PostgreSQL"],company_url:""}],
  education:[{id:1,school:"Tên trường Đại học",degree:"Kỹ sư / Cử nhân",field_of_study:"Công nghệ thông tin",start_year:2022,end_year:2026,grade:"",description:"Tập trung vào kỹ nghệ phần mềm và hệ thống thông tin.",school_url:""}],
  projects:[{id:1,title:"Digital Experience",slug:"digital-experience",tagline:"Nền tảng số hiện đại, nhanh và dễ sử dụng.",description:"Một sản phẩm full-stack được thiết kế từ trải nghiệm đến hạ tầng.",cover_url:"",live_url:"",source_url:"https://github.com",technologies:["Next.js","Django","PostgreSQL"],year:2026,is_featured:true,accent:"#8b5cf6"},{id:2,title:"Data Intelligence",slug:"data-intelligence",tagline:"Biến dữ liệu thô thành góc nhìn có giá trị.",description:"Dashboard trực quan cho dữ liệu thời gian thực.",cover_url:"",live_url:"",source_url:"",technologies:["Python","REST API","Docker"],year:2025,is_featured:true,accent:"#06b6d4"}],
  skills:[{id:1,name:"Next.js",category:"frontend",level:88,icon:"N"},{id:2,name:"TypeScript",category:"frontend",level:84,icon:"TS"},{id:3,name:"Django",category:"backend",level:86,icon:"Dj"},{id:4,name:"Python",category:"backend",level:90,icon:"Py"},{id:5,name:"PostgreSQL",category:"database",level:80,icon:"Pg"},{id:6,name:"Docker",category:"devops",level:76,icon:"D"}],
  soft_skills:[{id:1,name:"Giải quyết vấn đề",description:"Tìm đúng nguyên nhân trước khi tìm giải pháp.",icon:"brain"},{id:2,name:"Giao tiếp",description:"Trao đổi rõ ràng giữa kỹ thuật và sản phẩm.",icon:"message"},{id:3,name:"Tự học",description:"Chủ động đào sâu công nghệ và lĩnh vực mới.",icon:"sparkles"}],
  awards:[{id:1,title:"Thành tích nổi bật",issuer:"Đơn vị tổ chức",year:2025,description:"Thay nội dung này trực tiếp trong CMS.",credential_url:""}], certifications:[]
};
